### PR TITLE
Inline `copyto!` to fix Ref allocations

### LINKED ISSUE #946: Allocations in broadcasts with Ref
## Describe the bug
We're incurring allocations in broadcast statements involving the use of `Ref`.

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR applies `@inline` to `copyto!`, which was found to fix allocations with `Ref`s inside broadcast expressions, and adds tests. I'm going to try this out with ClimaAtmos to see if one more minor change is needed, too.

This fixes our `bycolumn` allocations with `Ref`s from 24576 bytes to 0.

Closes #946.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Thanks for the investigatory work, @simonbyrne!

File: test/Fields/field.jl [hunk 1]
```diff
@@ -468,3 +468,41 @@ end
...
+        Y = FieldFromNamedTuple(space, (; x = FT(2)))
+
+        # Plain broadcast
+        Yx = Y.x
+        foo!(Yx) # compile first
+        p = @allocated foo!(Yx)
+        @test_broken p == 0 # 16 bytes
+        # debug info:
+        # @info "space = $(nameof(typeof(space)))"
+        # @show p
```
Comment (charleskawczynski) [inline test/Fields/field.jl:501]: cc @simonbyrne, not sure why this is still allocating, does anything stick out to you?

Comment (charleskawczynski) [reply test/Fields/field.jl]: Fixed 🎉

**Comment by charleskawczynski** [comment]
Oops, looks like that doesn't pass the allocation tests with `--check-bounds=yes`, so I'll move these tests into a separate file.
