### PR TITLE
Bubble correction: Fix robustness

### LINKED ISSUE #1093: Robustness of bubble correction
## Describe the bug
As anticipated in #1063 , there are issues with robustness of the bubble correction with respect to the number of quadrature points. I wanted to keep things tidy and organized, so I decided to open up a separate issue for the robustness.

With the exclusion of the linear case (i.e., `Nq = 2`), the bubble correction seems to provide an improvement for even `Nq`s, but it gives worse results (when compared to the spectral space w/o bubble correction) for odd `Nq`s. 

## To Reproduce
I slightly modified the unit test to loop over different `Nq`s and we can see that with the exception of the linear case (i.e., `Nq = 2`), all even `Nq`s have a much better error tolerance than the odd ones.

The unit test that highlights this behavior can be found in the working branch [valeria/bubble-robustness](https://github.com/CliMA/ClimaCore.jl/tree/valeria/bubble-robustness), and is reported below: 

```julia
using LinearAlgebra, IntervalSets, UnPack
using ClimaComms
import ClimaCore: Domains, Topologies, Meshes, Spaces, Geometry, column

using Test

@testset "Bubble correction Nq robustness" begin

    FT = Float64
    no_bubble_rtols =
        (0.64, 0.19, 0.027, 0.0049, 0.0008, 0.00014, 2.33e-5, 3.97e-6, 6.77e-7)
    bubble_rtols = (
        1.8,
        0.38,
        2.33e-5,
        0.0097,
        1.98e-8,
        0.00028,
        1.7e-11,
        7.94e-6,
        1.55e-14,
    )
    Nqs = (2, 3, 4, 5, 6, 7, 8, 9, 10)
    for k in 1:length(Nqs)
        context = ClimaComms.SingletonCommsContext()
        radius = FT(3)
        ne = 1
        domain = Domains.SphereDomain(radius)
        mesh = Meshes.EquiangularCubedSphere(domain, ne)
        topology = Topologies.Topology2D(context, mesh)
        quad = Spaces.Quadratures.GLL{Nqs[k]}()
        no_bubble_space = Spaces.SpectralElementSpace2D(topology, quad)
        # surface area
        @test sum(ones(no_bubble_space)) ≈ FT(4pi * radius^2) rtol =
            no_bubble_rtols[k]
        bubble_space =
            Spaces.SpectralElementSpace2D(topology, quad; enable_bubble = true)

        @test sum(ones(bubble_space)) ≈ FT(4pi * radius^2) rtol =
            bubble_rtols[k]
    end

end
```

<details><summary>Project</summary>
<p>
Using the `test` project.

</p>
</details>

## Related issues / PRs
#1019  and #1063

### PR DESCRIPTION
**Pull request by valeriabarra**
This is a PR to address issue #1093 

Will close #1093

For the linear case the fix proposed is to divide the delta area, `Δarea`, by `Nq^2` so that the corrected Jacobians are not "overcorrected". That is, instead of adding the entire `Δarea` that is an element-wide contribution we redistribute a node-wide contribution. This fixes the issue and in fact the `@test_broken` passes (showing the fix). 

For the nonlinear case, we remove the `abs` in the `Δarea` calculation.

Summary of changes:

- [x] For the linear case, divide the delta area, `Δarea`, by `Nq^2
- [x] Updated docstring 
- [x] For the nonlinear case, remove  `abs` in the `Δarea` calculation.
- [x] Update unit tests by removing the `@test_broken` and updating tolerances.

Template:
- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

File: src/Spaces/spectralelement.jl [hunk 1]
```diff
@@ -183,7 +183,7 @@ geometric and numerical areas of each element match.
 Let ``\\Delta A^e := A^e_{exact} - A^e_{approx}``, then, in
 the case of linear elements, we correct ``W_{i,j} J^e_{i,j}`` by:
 ```math
-\\widehat{W_{i,j} J^e}_{i,j} = W_{i,j} J^e_{i,j} + \\Delta A^e * W_{i,j}  .
+\\widehat{W_{i,j} J^e}_{i,j} = W_{i,j} J^e_{i,j} / Nq^2 + \\Delta A^e * W_{i,j} / Nq^2 .
```
Comment (simonbyrne) [inline src/Spaces/spectralelement.jl:186]:
```suggestion
\\widehat{W_{i,j} J^e}_{i,j} = W_{i,j} J^e_{i,j} + \\Delta A^e * W_{i,j} / Nq^2 .
```

**Comment by valeriabarra** [comment]
@simonbyrne  this for now addresses the robustness issue. Can I introduce the new suggested CLI option to specify the tolerance in a different PR? 
I prefer to keep things organized and tidy. 
Ready for review. Thanks

File: src/Spaces/spectralelement.jl [hunk 2]
```diff
@@ -245,16 +245,15 @@ function SpectralElementSpace2D(
         Quadratures.quadrature_points(FT, quadrature_style)
     high_order_quad_points, high_order_quad_weights =
         Quadratures.quadrature_points(FT, high_order_quadrature_style)
+    tot_area = zero(FT)
```
Comment (simonbyrne) [inline src/Spaces/spectralelement.jl:248]: this doesn't appear to be used?

File: test/Spaces/sphere.jl [hunk 3]
```diff
@@ -66,18 +67,40 @@ end
...
+            FT(0.64f0),
+            FT(0.19f0),
+            FT(0.027f0),
+            FT(0.0049f0),
+            FT(0.0008f0),
+            FT(0.00014f0),
+            FT(2.4f-5),
+            FT(3.65f-6),
+            FT(4.05f-7),
+        )
```
Comment (simonbyrne) [inline test/Spaces/sphere.jl:80]: Looks like it is about O(Nq^2.5):
```
rtols = [35*0.5^(2.5*Nq) for Nq=2:10]
```

File: test/Spaces/sphere.jl [hunk 4]
```diff
@@ -66,18 +67,40 @@ end
...
+            FT(0.027),
+            FT(0.0008),
+            FT(2.33e-5),
+            FT(6.77e-7),
+            FT(1.98e-8),
+            FT(5.78e-10),
+            FT(1.7e-11),
+            FT(4.94e-13),
+            FT(1.53e-14),
+        )
```
Comment (simonbyrne) [inline test/Spaces/sphere.jl:103]: As I said on the call, we should increase the internal `high_order_Nq` so that these are all `O(eps(FT))`

File: test/Spaces/sphere.jl (hunk 3 above)
Comment (simonbyrne) [reply test/Spaces/sphere.jl:80]: these should be the same for both `Float64` and `Float32`

File: src/Spaces/spectralelement.jl (hunk 2 above)
Comment (valeriabarra) [reply src/Spaces/spectralelement.jl:248]: Yes, indeed, I was already removing that. It was just there for my debugging purposes.

**Comment by valeriabarra** [comment]
Thanks @simonbyrne . I intend to add the suggested CLI option for arbitrary bubble order in a separate follow-up PR. I think this is ready to merge. Thanks

**Review by simonbyrne — APPROVED** [review]
