### PR TITLE
Fix CommonSpaces and MPI

### LINKED ISSUE #2175: `CommonSpaces` are not compatible with MPI
To reproduce, run the `unit_common_spaces.jl` test to initialize the MPI context. To do so, just add 
```julia
ClimaComms.init(ClimaComms.context())
```
before the testset. 

Run the code with mpi, the result is:
```julia
  AssertionError: context isa ClimaComms.SingletonCommsContext
  Stacktrace:
    [1] _IntervalTopology(context::ClimaComms.MPICommsContext{ClimaComms.CPUSingleThreaded, MPI.Comm}, mesh::ClimaCore.Meshes.IntervalMesh{ClimaCore.Meshes.Uniform, ClimaCore.Domains.IntervalDomain{ClimaCore.Geometry.ZPoint{Float64}, Tuple{Symbol, Symbol}}, LinRange{ClimaCore.Geometry.ZPoint{Float64}, Int64}, Nothing})
      @ ClimaCore.Topologies ~/repos/ClimaCore.jl/src/Topologies/interval.jl:46
    [2] (::ClimaCore.Topologies.var"#1#2"{ClimaComms.MPICommsContext{ClimaComms.CPUSingleThreaded, MPI.Comm}, ClimaCore.Meshes.IntervalMesh{ClimaCore.Meshes.Uniform, ClimaCore.Domains.IntervalDomain{ClimaCore.Geometry.ZPoint{Float64}, Tuple{Symbol, Symbol}}, LinRange{ClimaCore.Geometry.ZPoint{Float64}, Int64}, Nothing}})()
      @ ClimaCore.Topologies ~/repos/ClimaCore.jl/src/Topologies/interval.jl:37
    [3] get!
      @ ./dict.jl:458 [inlined]
    [4] IntervalTopology
      @ ~/repos/ClimaCore.jl/src/Topologies/interval.jl:36 [inlined]
    [5] ExtrudedCubedSphereGrid(::Type{Float64}; z_elem::Int64, z_min::Int64, z_max::Int64, radius::Int64, h_elem::Int64, n_quad_points::Int64, device::ClimaComms.CPUSingleThreaded, context::ClimaComms.MPICommsContext{ClimaComms.CPUSingleThreaded, MPI.Comm}, stretch::ClimaCore.Meshes.Uniform, hypsography_fun::ClimaCore.CommonGrids.var"#4#6", global_geometry::ClimaCore.Geometry.ShallowSphericalGlobalGeometry{Float64}, quad::ClimaCore.Quadratures.GLL{4}, h_mesh::ClimaCore.Meshes.EquiangularCubedSphere{ClimaCore.Domains.SphereDomain{Float64}, ClimaCore.Meshes.NormalizedBilinearMap}, h_topology::ClimaCore.Topologies.Topology2D{ClimaComms.MPICommsContext{ClimaComms.CPUSingleThreaded, MPI.Comm}, ClimaCore.Meshes.EquiangularCubedSphere{ClimaCore.Domains.SphereDomain{Float64}, ClimaCore.Meshes.NormalizedBilinearMap}, CartesianIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, LinearIndices{3, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}}, Vector{Tuple{Int64, Int64, Int64, Int64, Bool}}, Vector{Tuple{Int64, Int64, Int64, Int64, Bool}}, Vector{Tuple{Int64, Int64}}, Vector{Int64}, Vector{Tuple{Bool, Int64, Int64}}, Vector{Int64}, Vector{Int64}, @NamedTuple{}, Vector{Tuple{Int64, Int64}}}, horizontal_layout_type::Type, z_mesh::ClimaCore.Meshes.IntervalMesh{ClimaCore.Meshes.Uniform, ClimaCore.Domains.IntervalDomain{ClimaCore.Geometry.ZPoint{Float64}, Tuple{Symbol, Symbol}}, LinRange{ClimaCore.Geometry.ZPoint{Float64}, Int64}, Nothing}, enable_bubble::Bool)
      @ ClimaCore.CommonGrids ~/repos/ClimaCore.jl/src/CommonGrids/CommonGrids.jl:192
    [6] ExtrudedCubedSphereSpace(::Type{Float64}; staggering::CellCenter, kwargs::@Kwargs{z_elem::Int64, z_min::Int64, z_max::Int64, radius::Int64, h_elem::Int64, n_quad_points::Int64, horizontal_layout_type::UnionAll})
      @ ClimaCore.CommonSpaces ~/repos/ClimaCore.jl/src/CommonSpaces/CommonSpaces.jl:121
    [7] ExtrudedCubedSphereSpace
      @ ~/repos/ClimaCore.jl/src/CommonSpaces/CommonSpaces.jl:121 [inlined]
    [8] #ExtrudedCubedSphereSpace#1
      @ ~/repos/ClimaCore.jl/src/CommonSpaces/CommonSpaces.jl:119 [inlined]
    [9] macro expansion
      @ ~/repos/ClimaCore.jl/test/CommonSpaces/unit_common_spaces.jl:32 [inlined]
   [10] macro expansion
      @ ~/.julia/juliaup/julia-1.11.3+0.x64.linux.gnu/share/julia/stdlib/v1.11/Test/src/Test.jl:1704 [inlined]
   [11] top-level scope
      @ ~/repos/ClimaCore.jl/test/CommonSpaces/unit_common_spaces.jl:23
   [12] include(mod::Module, _path::String)
      @ Base ./Base.jl:557
   [13] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:323
   [14] _start()
```

Something is not initialized with the correct context

### PR DESCRIPTION
**Pull request by Sbozzolo**
The `CommonGrids` module passes down the context to all the grid it creates. This is a problem for IntervalTopology, because it can only be created with Singletons.

This commit fixes this issue and adds test checking that we can create CommonSpaces with MPI and CUDA

Closes #2175

### CODE REVIEW

File: test/CommonSpaces/unit_common_spaces.jl [hunk 1]
```diff
@@ -34,7 +37,7 @@ using Test
         h_elem = 10,
         n_quad_points = 4,
         horizontal_layout_type = DataLayouts.IJHF,
-        staggering = Grids.CellCenter(),
+        staggering = CommonSpaces.CellCenter(),
```
Comment (charleskawczynski) [inline test/CommonSpaces/unit_common_spaces.jl:40]: Can you please revert this? `CellCenter`/`CellFace` is not an object defined in `CommonSpaces`.

Comment (Sbozzolo) [reply test/CommonSpaces/unit_common_spaces.jl:40]: I thought we decided to re-export it and use it directly from `CommonSpaces` when working with `CommonSpaces`. 

This change ensures that those looking at this code have a good pattern to copy.

Comment (charleskawczynski) [reply test/CommonSpaces/unit_common_spaces.jl:40]: I'm fine with re-exporting it, but that means that users shouldn't have to qualify it. That's not where it comes from, I think it makes the most sense to qualify objects from their origin, not from wrappers. For example, we did this a lot when stripping out dependencies in ClimaTimesteppers when moving from DiffEqBase to SciMLBase, which is where the methods originate from.

Comment (Sbozzolo) [reply test/CommonSpaces/unit_common_spaces.jl:40]: I removed the qualifier.

Comment (charleskawczynski) [reply test/CommonSpaces/unit_common_spaces.jl]: Thank you!

File: test/CommonSpaces/unit_common_spaces.jl [hunk 2]
```diff
@@ -75,14 +78,17 @@ using Test
...
-    space = ColumnSpace(;
-        z_elem = 10,
-        z_min = 0,
-        z_max = 1,
-        staggering = Grids.CellCenter(),
-    )
-    grid = Spaces.grid(space)
-    @test grid isa Grids.FiniteDifferenceGrid
+    # Column spaces are not supported with MPI
+    if !(ClimaComms.context() isa ClimaComms.MPICommsContext)
```
Comment (charleskawczynski) [inline test/CommonSpaces/unit_common_spaces.jl:82]: Does this just not work?

**Review by charleskawczynski — APPROVED** [review]
Overall this PR looks like a good set of fixes / improvements.

File: test/CommonSpaces/unit_common_spaces.jl (hunk 2 above)
Comment (Sbozzolo) [reply test/CommonSpaces/unit_common_spaces.jl:82]: I had this error:
```
  AssertionError: Columns can only be created on Singleton contextes.
```

But maybe it's because I am not caught up to main. Let me try rebasing

Comment (Sbozzolo) [reply test/CommonSpaces/unit_common_spaces.jl:82]: Actually, I added that `@assert`. I'll verify again

Comment (Sbozzolo) [reply test/CommonSpaces/unit_common_spaces.jl]: I added the assert because creating columns in MPI settings is not possible:
https://github.com/CliMA/ClimaCore.jl/blob/c19162a39c1c8d0b5465449fc55ec78ac3632bc2/src/Topologies/interval.jl#L46

Comment (Sbozzolo) [reply test/CommonSpaces/unit_common_spaces.jl]: Here's the failing build: https://buildkite.com/clima/climacore-ci/builds/5255
