### PR TITLE
Fix distributed remapping bug

### LINKED ISSUE #2108: Distributed remapping interpolation bug
Our unit tests seem to be flaky: https://buildkite.com/clima/climacore-ci/builds/4846#0193e0c9-7253-46f0-b029-699ab6c5bf95 (the corresponding PR does not touch anything related to distributed remapping / interpolation).

### PR DESCRIPTION
**Pull request by Sbozzolo**
#2108 partially describes the odissey I went through to understand and fix this bug.

After discussing this with folks at MPI.jl (https://github.com/JuliaParallel/MPI.jl/issues/892), a potential problem was identified:
```
remapper._interpolated_values[remapper.colons..., begin]
```
in the `ClimaComms.reduce!` call allocates a new copy. This can mess up CUDA's synchronization, so that the correct data is not sent over. The simple solution is to use `view` instead of slices.

In addition to this, this PR changes `interpolate` to use `interpoalte!`, which leads much simpler code (the reason it was not done this way originally is because `interpolate!` is a more recent addition and behaved slightly differently).

Closes #2108 
Closes #2132

### CODE REVIEW

**Comment by Sbozzolo** [comment]
It looks like that my earlier [tests](https://buildkite.com/clima/climacore-ci/builds/5086) passed just by luck :(

File: src/Remapping/distributed_remapping.jl [hunk 1]
```diff
@@ -777,38 +754,26 @@ function _collect_interpolated_values!(
     if only_one_field
         ClimaComms.reduce!(
```
Comment (vchuravy) [inline src/Remapping/distributed_remapping.jl:755]: Where is the synchronization of the CUDA stream?

https://github.com/CliMA/ClimaComms.jl/blob/c968350313d5dc81d007721bc27a4bc9c97a79e3/ext/ClimaCommsMPIExt.jl#L69
