### PR TITLE
Fix getidx for GradientC2F with SetValue bcs

### LINKED ISSUE #994: Spatially varying BC dont work for grads?
```julia
using ClimaCore

FT = Float64
zmin = FT(1.0)
zmax = FT(2.0)
xlim = FT.((0.0, 10.0))
ylim = FT.((0.0, 1.0))
zlim = FT.((zmin, zmax))
nelements = (1, 1, 5)
npolynomial = 3
domain_x = ClimaCore.Domains.IntervalDomain(
    ClimaCore.Geometry.XPoint(xlim[1]),
    ClimaCore.Geometry.XPoint(xlim[2]);
    periodic = true,
)
domain_y = ClimaCore.Domains.IntervalDomain(
    ClimaCore.Geometry.YPoint(ylim[1]),
    ClimaCore.Geometry.YPoint(ylim[2]);
    periodic = true,
)
plane = ClimaCore.Domains.RectangleDomain(domain_x, domain_y)

mesh =
    ClimaCore.Meshes.RectilinearMesh(plane, nelements[1], nelements[2])
grid_topology = ClimaCore.Topologies.Topology2D(mesh)
quad = ClimaCore.Spaces.Quadratures.GLL{npolynomial + 1}()
horzspace = ClimaCore.Spaces.SpectralElementSpace2D(grid_topology, quad)


vertdomain = ClimaCore.Domains.IntervalDomain(
    ClimaCore.Geometry.ZPoint(zlim[1]),
    ClimaCore.Geometry.ZPoint(zlim[2]);
    boundary_tags = (:bottom, :top),
)
vertmesh = ClimaCore.Meshes.IntervalMesh(vertdomain, nelems = nelements[3])
vert_center_space = ClimaCore.Spaces.CenterFiniteDifferenceSpace(vertmesh)

hv_center_space =
    ClimaCore.Spaces.ExtrudedFiniteDifferenceSpace(horzspace, vert_center_space)

surface_field = ClimaCore.Fields.zeros(horzspace)

ψ = ClimaCore.Fields.ones(hv_center_space)
value = surface_field # same type/instance of underlying space as horizontal space of \psi
```
Then, let's try and apply value as a boundary flux to divergence:
```julia
gradc2f_no_bc = ClimaCore.Operators.GradientC2F()
divf2c = ClimaCore.Operators.DivergenceF2C(
                  top = ClimaCore.Operators.SetValue(ClimaCore.Geometry.WVector.(value)),
                  bottom = ClimaCore.Operators.SetValue(ClimaCore.Geometry.WVector(FT(0.0))),
              )
@. divf2c(gradc2f_no_bc(ψ)) # runs
```
Another scenario is a spatially varying state BC - i.e. apply it as a boundary to the gradient:
```julia
gradc2f = ClimaCore.Operators.GradientC2F(top = ClimaCore.Operators.SetValue(value), bottom = ClimaCore.Operators.SetValue(0.0))
gradc2f.(ψ) # fails
```
Any idea why spatially varying BC doent seem to work for gradients?

### LINKED ISSUE #2089: Add finite difference operator unit tests
We should really add unit tests for our finite difference operators (i.e., `Operators.getidex` for our operators). We can do this using LazyBroadcast, and we can test that the stencil is correct at the index level.

### PR DESCRIPTION
**Pull request by charleskawczynski**
Closes #994. cc @kmdeck.

In a followup, we can fix #2089, which would have caught this error.

### CODE REVIEW

File: src/Operators/finitedifference.jl [hunk 1]
```diff
@@ -3622,8 +3622,13 @@ end
...
 ) = field[]
-@inline getidx(parent_space, field::Fields.PointField, loc::Location, idx) =
-    field[]
+@inline getidx(
+    parent_space,
+    field::Fields.PointField,
+    loc::Location,
+    idx,
+    hidx,
+) = field[]
```
Comment (dennisYatunin) [inline src/Operators/finitedifference.jl:3631]: Is this not a duplicate of lines 3618--3624?

**Review by dennisYatunin — APPROVED** [review]
The `idx` -> `hidx` change looks correct, but the other change seems unnecessary.

File: src/Operators/finitedifference.jl (hunk 1 above)
Comment (charleskawczynski) [reply src/Operators/finitedifference.jl:3631]: It is! I don't know how the one I changed could ever get called, though, I think all of these methods follow the same api, up to the `hidx`. I'll try removing it and see what CI says.

Comment (charleskawczynski) [reply src/Operators/finitedifference.jl:3631]: This change only came along because I searched for any other mistakes following the first, and I noticed the different number of args.
