### PR TITLE
strip out unnecessary space metadata in spectral element operators

### LINKED ISSUE #1226: Composed operators use too much parameter space
## Describe the bug
When composing multiple operators on the GPU, I often get the error
```
ERROR: Failed to compile PTX code (ptxas exited with code 255)
Invocation arguments: --generate-line-info --verbose --gpu-name sm_60 --output-file /tmp/jl_WvsZ8X6v8x.cubin /tmp/jl_WZ85G5u5Yp.ptx
...
uses too much parameter space (0x1208 bytes, 0x1100 max).
ptxas fatal   : Ptx assembly aborted due to errors
If you think this is a bug, please file an issue and attach /tmp/jl_WZ85G5u5Yp.ptx
```

What this is saying is that the GPU kernel parameters (the information passed from the CPU to the GPU kernel on each launch) being too large. The limit appears to be about 4KB, but our vector Laplacian operator is over 8KB.

This is caused by our representation of the broadcasted expression trees: we duplicate a lot of information. Each `Field` carries its space, as does each node in the expression tree.

Some ways we can fix this:
- remove the space when we Adapt the `Field` (we could have a special `DeviceField`?).
  - the main challenge here is how to make `getidx` work (in particular the `half` offset/periodic pieces)
- remove the space when we Adapt the bc (except for the top-level?)
  - this gets challenging as some operations change spaces: FD can alternate center <-> face, SE can change order (but this is not yet supported on GPUs).

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #1226.

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

File: src/Operators/spectralelement.jl [hunk 1]
```diff
@@ -426,7 +493,8 @@ Base.@propagate_inbounds function set_node!(
     fv = Fields.field_values(field)
     fv[i, j, nothing, v, h] = val
 end
-
+set_node!(field, ij, slabidx, val) =
```
Comment (charleskawczynski) [inline src/Operators/spectralelement.jl:496]: Do we need this?

File: test/Operators/hybrid/cuda.jl [hunk 2]
```diff
@@ -91,14 +91,28 @@ end
...
+    coords = Fields.coordinate_field(hv_face_space_gpu)
+    z = coords.z
 
     gradc = Operators.GradientF2C()
 
     @test parent(Geometry.WVector.(gradc.(z))) ≈
           parent(Geometry.WVector.(ones(hv_center_space_gpu)))
-end
 
+
```
Comment (charleskawczynski) [inline test/Operators/hybrid/cuda.jl:102]: Can we add a comment what this issue this fixes? (https://github.com/CliMA/ClimaCore.jl/issues/1226)

**Review by charleskawczynski — APPROVED** [review]
Overall looks good!

My preference would be to eagerly unpack fieldvalues so that we don't accidentally grab the field space in some broadcast expressions but not others. But it should be fine assuming it's thoroughly tested.

My only other concern is the `set_node!(field, ij, slabidx, val) = set_node!(axes(field), field, ij, slabidx, val)` fallback, won't we want to always avoid this?

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

File: src/Operators/spectralelement.jl [hunk 3]
```diff
@@ -233,6 +233,53 @@ Base.@propagate_inbounds _resolve_operator_args(slabidx, arg, xargs...) = (
...
+) where {Style}
+    current_space = axes(bc)
+    if current_space == parent_space
+        new_space = PlaceholderSpace()
+    else
+        new_space = current_space
+    end
+    return Base.Broadcast.Broadcasted{Style}(
+        bc.f,
+        map(arg -> strip_space(arg, current_space), bc.args),
```
Comment (charleskawczynski) [inline src/Operators/spectralelement.jl:263]: Does this need to be recursive?

Comment (simonbyrne) [reply src/Operators/spectralelement.jl:263]: Probably, but it's not in a tight loop, so we're probably fine.

Comment (charleskawczynski) [reply src/Operators/spectralelement.jl:263]: Just so I understand correctly, does this mean that if a BC expression has 8 levels of recursion, then this would strip it down to 7?

Comment (charleskawczynski) [reply src/Operators/spectralelement.jl:263]: Ah, ok, got it.

**Comment by simonbyrne** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]
