### PR TITLE
Tr/minor fixes

### LINKED ISSUE #2320: `field2array` error statement is inaccurate
The `field2array`  error when the field is not a field of scalars is inaccurate. 

```julia
julia> ClimaCore.Fields.field2array(ClimaCore.Fields.fill((1.0, 2.0), ClimaCore.Spaces.PointSpace(ClimaCore.Geometry.YPoint(0.5))))
ERROR: unable to use field2array because each Field element is represented by 0 array elements (must be 1)
Stacktrace:
```

I think this is caused by 
```
f_axis_size = sizeof(eltype(parent(field))) ÷ sizeof(eltype(field))
        error("unable to use field2array because each Field element is \
               represented by $f_axis_size array elements (must be 1)")
```

which should be 

```
f_axis_size = sizeof(eltype(field)) ÷ sizeof(eltype(parent(field))) 
```

### LINKED ISSUE #2337: `Spaces.nlevels` doesn't error for invalid level input arg
```
Build an arbitrary extruded geometry (in this case, spherical) simulation and query some level information : 

julia> Spaces.axes(Y.c.ρ)
CenterExtrudedFiniteDifferenceSpace:
  context: SingletonCommsContext using CPUSingleThreadedSingletonCommsContext using CPUSingleThreaded
  horizontal:
    mesh: 6×6×6-element EquiangularCubedSphere of SphereDomain: radius = 6.371e6
    node_horizontal_length_scale: 512229.34
    element_horizontal_length_scale: 1.536688e6
    quadrature: 4-point Gauss-Legendre-Lobatto quadrature
  vertical:
    mesh: 10-element IntervalMesh of IntervalDomain: z ∈ [0.0,30000.0] (:bottom, :top)

julia> test_face_field
Float32-valued Field:
  Float32[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

julia> size(parent(test_face_field))
(11, 4, 4, 1, 216)

julia> Spaces.nlevels(test_face_field)
11

julia> Fields.level(test_face_field, 11+half)
Float32-valued Field:
  Float32[-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0  …  -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0]

julia> Fields.level(test_face_field, 10+half)
Float32-valued Field:
  Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

julia> Fields.level(test_face_field, 200+half)
Float32-valued Field:
  Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  1.11116f-36, 163965.0, 9332.46, 9.26442f-23, 9.26442f-23, 9.49672f-18, 3.06812f-10, 2.37873f6, 9.67983f-12, 1.08037f-40]
```

I'd expect the last line to error since the level ind exceeds `Spaces.nlevels(field_of_interest)`.

### LINKED ISSUE #2348: Inconsistent AxisVector indexing
Indexing a 1d axis vector behaves differently than indexing a 2d axis vector:

```
julia> v1 = ClimaCore.Geometry.Covariant1Vector(1.0)
1-element ClimaCore.Geometry.Covariant1Vector{Float64} with indices ClimaCore.Geometry.CovariantAxis{(1,)}():
 1.0

julia> v2 = ClimaCore.Geometry.Covariant12Vector(1.0, 2.0)
2-element ClimaCore.Geometry.Covariant12Vector{Float64} with indices ClimaCore.Geometry.CovariantAxis{(1, 2)}():
 1.0
 2.0

julia> v2.u
u₁
u₂
u₃
julia> v2.u₃
0.0

julia> v1.u₃
1.0
```

Ran on ClimaCore v0.14.34

```
Julia Version 1.10.9
Commit 5595d20a287 (2025-03-10 12:51 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```

### PR DESCRIPTION
**Pull request by imreddyTeja**
This PR addresses three issues:
1. An incorrect error message is shown when `field2array` is called with incompatible elements. 
2. For face fields, the `level` function does not throw `BoundsError`s
3. The indexing behavior for AxisTensors is inconsistent. With any 1d axis tensor vs 2d and 3d.

For the first issue, the message itself is corrected.
For the second issue, tests are added for `level(::Field)`. 
The fix for the second issue requires removing an `@inbounds`, so there may be a performance penalty.

This PR also bumps the UnrolledUtilities compat to v0.1.8. v0.1.7 adds a lot of useful unrolled_functions, including `unrolled_findfirst`, but the downgrade will throw JET errors unless using v0.1.8

Closes #2337 
Closes #2320 
Closes #2348

### CODE REVIEW

File: src/Spaces/finitedifference.jl [hunk 1]
```diff
@@ -145,3 +145,10 @@ Base.@propagate_inbounds function level(
     local_geometry = level(local_geometry_data(space), v)
     PointSpace(ClimaComms.context(space), local_geometry)
 end
+function issubspace(subspace::PointSpace, space::FiniteDifferenceSpace)
+    all_local_geometry = local_geometry_data(space)
+    unrolled_any(
+        v -> subspace.local_geometry === level(all_local_geometry, v),
+        1:nlevels(space),
+    )
```
Comment (charleskawczynski) [inline src/Spaces/finitedifference.jl]: I'm not sure that we want to unroll over all `nlevels` for this. Isn't it sufficient to check the first level? When would it not be?

Comment (imreddyTeja) [reply src/Spaces/finitedifference.jl]: I thought the local geometry can vary spatially. For example:

```
julia> DataLayouts.level(Spaces.local_geometry_data(space), 1)[].coordinates
ZPoint(0.5)

julia> DataLayouts.level(Spaces.local_geometry_data(space), 3)[].coordinates
ZPoint(2.5)

julia> Fields.local_geometry_field(Fields.level(space, 1)).coordinates
ClimaCore.Geometry.ZPoint{Float64}-valued Field:
  z: [0.5]

julia> Fields.local_geometry_field(Fields.level(space, 3)).coordinates
ClimaCore.Geometry.ZPoint{Float64}-valued Field:
  z: [2.5]
```

Comment (charleskawczynski) [reply src/Spaces/finitedifference.jl]: Yeah, I suppose it's safe to do the comparison over every point (even checking the range is still subject errors). But, we still probably don't want to unroll this call, since the result is not compile time known and `nlevels` can be quite large.

Comment (imreddyTeja) [reply src/Spaces/finitedifference.jl]: I guess this method is not really needed. Its only use in src is to check broadcasting shapes, which already has  unique methods for `PointSpaces`.

Comment (charleskawczynski) [reply src/Spaces/finitedifference.jl]: Yeah, I don't think it's likely that we'll fall into such an error, but it is an extra layer of protection.

On the one hand, I don't think that this can be easily determined, with our current design, at compile-time. Ideally, we could add some sort of compile-time switches into our code that would allow / enforce these checks at runtime, and we could use it as a debugging feature. But it might be a hefty amount of work to make that feature available.

Comment (imreddyTeja) [reply src/Spaces/finitedifference.jl]: I'm not quite sure why I used unrolling here... do you think I should just remove this functionality, or leave it without unrolling? The only argument I have for keeping it is that if it exists for the extruded spectral element spaces, I'd expect it to also exist for finite difference spaces.

Comment (charleskawczynski) [reply src/Spaces/finitedifference.jl]: I think the performance is likely fine without the unrolling, since the `===` comparison is likely pretty fast.

The only issue that I could see is that this operation is not compile-time known, and the logic of where this is called includes a check that the spaces are compatible (we error if they're not). If the check is not compile-time known, then it won't work inside a cuda kernel (this check is currently performed before the kernel is launched, but that won't be the case and it will need to work inside a cuda kernel with my `columnwise!` design, so there may be clashes with that).

File: src/Fields/Fields.jl [hunk 2]
```diff
@@ -517,7 +517,7 @@ Base.@propagate_inbounds function level(
     v::PlusHalf,
 )
     hspace = level(axes(field), v)
-    @inbounds data = level(field_values(field), v.i + 1)
+    data = level(field_values(field), v.i + 1)
```
Comment (akshaysridhar) [inline src/Fields/Fields.jl:520]: Do we know what the performance penalty , if any, here might be ?

Comment (akshaysridhar) [reply src/Fields/Fields.jl:520]: @dennisYatunin pointed out we call the outer function with propagate_inbounds; this is not an issue. Thanks @imreddyTeja
